### ISSUE TITLE
config file of zkevm-bridge-service missing when deploy zkevm 

### ISSUE THREAD

**Issue by dylanzkl** [0xPolygon/polygon-docs-old#109]
I'm deploying a polygon zkEVM following this official [guide](https://docs.polygon.technology/zkEVM/get-started/deploy-zkevm/). But I can't start up the zkevm-bridge-service due to config file missing and I can't find any clue in the docs to guide me to figure out how to config the zkevm-bridge-service.

**Comment by kmurphypolygon** [comment]
Hi @dylanzkl 

We're looking into this for you.

Please be aware we just updated our whole doc site so we are expecting to be making a lot of fixes in the next weeks. Please be patient with us.

I will raise a ticket for this one.

Thank you.

**Comment by kmurphypolygon** [comment]
Ticket for docs team: https://polygon.atlassian.net/browse/TKDW-26

**Comment by kmurphypolygon** [comment]
Hi @dylanzkl so sorry for the delay on this. Our systems, including the bridge services, are going through some major releases right now so this zkEVM quick start is likely to change fundamentally very soon. 
Please keep an eye on the docs for changes but I'm closing this for now.
In the meantime, you could check out some of our CDK validium/rollup quick starts and deployment guides: https://docs.polygon.technology/cdk/get-started/quickstart-validium/

**Comment by kmurphypolygon** [comment]
Closing as unlikely we will fix this as it stands now.
