### ISSUE TITLE
Mint NFT guide is outdated

### ISSUE THREAD

**Issue by mbledkowski** [0xPolygon/polygon-docs-old#123]
Hello,
The Mint NFT guide (https://docs.polygon.technology/tools/storage/nftstorage/#deploy-the-smart-contract-to-polygon) is out of date.

It uses openzeppelin 4.x, where 5.x is available, which introduced breaking changes; and uses almost 2 years old solidity version.
This makes it hard for newcomers (like myself) to develop anything useful, as most of my time is spent on researching, how to migrate code from 4.x to 5.x.

I found both official hardhat, and openzeppelin documentation way more useful.

Best regards,
Maciej Błędkowski

**Comment by kmurphypolygon** [comment]
Hi, thanks for your comment @mbledkowski 

We have just migrated our docs from the old system and are currently in the process of doing a total renovation of the **Developer tools** section so we expected to see some old content like this. Please keep your eye on this section over the next few weeks as you should see some major improvements.

Thank you again for your contribution.

**Comment by kmurphypolygon** [comment]
@rahuldamodar94 one for us to look at soon as part of this ticket: https://polygon.atlassian.net/browse/TKLP-25

**Comment by kmurphypolygon** [comment]
I'm going to remove this doc for now because it is extremely old and we will look at replacing it in the future. 

Thank you for your input and please let us know if you see anything else or you need any more assistance.

Have a great weekend :) @mbledkowski
