### ISSUE TITLE
Crossmint guide is missing from the new Polygon PoS docs

### ISSUE THREAD

**Issue by rohit-710** [0xPolygon/polygon-docs-old#129]
I wrote a PR that got merged by @cerberushades which added Crossmint as one of the tools to deploy a Smart Contract on Polygon. 

It seems like it is missing after the migration was done. 

https://docs.polygon.technology/pos/how-to/smart-contracts/

Would it be possible for you to recover my old PR and add it here or do I have to make another PR?

**Comment by kmurphypolygon** [comment]
Hi @rohit-710 can you find your PR in here please: https://github.com/0xPolygon/wiki and I'll double check if we have it now but it's hidden somewhere. Please ping me directly or post the link here. Thank you.

**Comment by rohit-710** [comment]
It returns a 404 not found error when I open that link. I think the repo is probably private. 
https://github.com/0xPolygon/wiki/pull/184

But this should be the original PR

**Comment by kmurphypolygon** [comment]
Thanks @rohit-710 this is enough. I'll get back to you shortly.

**Comment by kmurphypolygon** [comment]
One question please @rohit-710 do you have this tutorial live on your site currently?

**Comment by rohit-710** [comment]
If you are referring to whether the tool is live on Polygon, then yes. But that specific tutorial is not on our Website or Docs. I wrote it specifically for the Polygon Docs

**Comment by kmurphypolygon** [comment]
Hi @rohit-710 I added it back, it should be live in the next day or so. Please check the Developer tools/Smart contracts section: https://github.com/0xPolygon/polygon-docs/pull/134

**Comment by rohit-710** [comment]
Hey @kmurphypolygon , thank you so much for the speedy fix! Glad to see that it has been added to the docs again!

**Comment by kmurphypolygon** [comment]
No worries @rohit-710 it's a pleasure.
Let us know if you see anything else :)

**Comment by rohit-710** [comment]
Hey @kmurphypolygon, just following up here! I am unable to see the doc on the PoS docs. Let me know if you need any help!

**Comment by kmurphypolygon** [comment]
It's here @rohit-710 : https://docs.polygon.technology/tools/smart-contracts/crossmint/

**Comment by rohit-710** [comment]
Hey @kmurphypolygon thank you so much for the update!
Would it be possible to add it under this as well? https://docs.polygon.technology/pos/how-to/smart-contracts/

**Comment by kmurphypolygon** [comment]
Hi @rohit-710 thanks for asking. I'm quite new and I wasn't aware of this section. We will make a decision about whether to move these too. Please give us some time on this.

**Comment by rohit-710** [comment]
Got it, thank you so much! Happy to help however I can
