### ISSUE TITLE
Validium - Sepolia guide

### ISSUE THREAD

**Issue by JanBajecDev** [0xPolygon/polygon-docs-old#240]
Hey i found a few typos in validium sepolia guid
https://docs.polygon.technology/cdk/get-started/deploy-validium/node/run-node-services/#run-the-node

should be "cd ~/cdk-validium/cdk-data-availability" instead of cd ~/cdk-validium/cdk-data-availability-0.0.3

should be "cd ~/cdk-validium/zkevm-bridge-service-0.3.1" instead of cd "~/cdk-validium/zkevm-bridge-service"

This one was cousing me problems with running the DAC -> https://docs.polygon.technology/cdk/get-started/deploy-validium/node/configure-deployment/#configure-the-dac

tomlq -i -t --arg CDK_VALIDIUM_ADDRESS "$CDK_VALIDIUM_ADDRESS" '.L1.CDKValidiumAddress = $CDK_VALIDIUM_ADDRESS' /tmp/cdk/dac-config.toml
tomlq -i -t --arg CDK_VALIDIUM_ADDRESS "$CDK_VALIDIUM_ADDRESS" '.L1.DataCommitteeAddress = $CDK_VALIDIUM_ADDRESS' /tmp/cdk/dac-config.toml
  
here its twice CDK_VALIDIUM_ADDRESS instead of DataCommitteeAddress

https://docs.polygon.technology/cdk/get-started/deploy-validium/node/configure-deployment/#configure-bridge-service

tomlq -i -t --arg CDK_DATA_COMMITTEE_CONTRACT_ADDRESS "$CDK_DATA_COMMITTEE_CONTRACT_ADDRESS" '.NetworkConfig.L2PolygonBridgeAddresses = [$CDK_DATA_COMMITTEE_CONTRACT_ADDRESS]' /tmp/cdk/bridge-config.toml

here CDK_DATA_COMMITTEE_CONTRACT_ADDRESS is mapped to L2PolygonBridgeAddresses instead of the bridge

**Comment by kmurphypolygon** [comment]
Thank you @JanBajecDev 

- This one looks ok: cd /cdk-validium/zkevm-bridge-service-0.3.1
- The problematic environment variables are about to be fixed in a new PR: https://github.com/0xPolygon/polygon-docs/pull/241
- The first one I fixed and one other I noticed.

We look forward to more of your contributions.
