### ISSUE TITLE
Unable to run ZKEVM using Polygon CDK

### ISSUE THREAD

**Issue by sahil3vedi** [0xPolygon/polygon-docs-old#273]
_**Note:** This query has been shared by a user via dev-support. The concerned docs are regarding zkRollup deployments with CDK: https://docs.polygon.technology/cdk/get-started/deploy-rollup/intro/_ 

Hey team,

Due to the frequent updates to the Polygon CDK repositories it seems like the documentation is not in line with the latest codebase. I tried to follow the documentation best I could and get things running, few notable deviations I took:

- Used `create_rollup_parameters.json` and `deploy_parameters.json` 
- Deployed on `sepolia` using the `deploy:testnet:v2:sepolia` script.
- Used Sepolia chainId and RPC wherever required
- Couldnt figure out what `polygonZkEVMAddress` was in V2 so assumed it was `polygonRollupManager` - most likely where my problems are coming from but I couldn't really find any documentation to help me with this. So I added both to the `l1Config` in `public.genesis.config.json`

Server Details:
- Ubuntu Server 22.04 LTS
- 16GB RAM with a 4-core CPU
- AMD64 architecture system

PFA the issue I am currently facing.

Looking forward to your response.

Thanks,
Van H.
Founder @HeimLabs

**Comment by kmurphypolygon** [comment]
Hi @sahil3Vedi thanks so much for your issue. We are also aware of the problems and are taking steps to update this part of the documentation hopefully in the next few weeks. I will keep this issue open and advise you at the time we make the changes.

**Comment by kmurphypolygon** [comment]
Hi @sahil3Vedi I'm so sorry for the delay in the documentation update. I'm just wondering if you can spin up the Kurtosis option instead: https://docs.polygon.technology/cdk/get-started/quickstart/deploy-stack/

**Comment by kmurphypolygon** [comment]
Hi @sahil3Vedi we made some changes today to the doc flow and will be pushing to live shortly. We're still working on the services part but the rest should be OK.

I wonder if you could test the flow now and let us know how you get on.

I'm going to close this ticket for now but feel free to open a new issue at any time.

Again, so sorry for the delay on this one.

https://docs.polygon.technology/cdk/get-started/deploy-rollup/intro/

cc: @BrianSeong99
