### ISSUE TITLE
(Missing) Bridging instructions for CDK Rollups

### ISSUE THREAD

**Issue by sahil3vedi** [0xPolygon/polygon-docs-old#305]
Hi, 

While we have bridging covered in the CDK Validium quickstart tutorial, there seems to be no mention of setting up a Bridge Service / UI with any of the CDK Rollup tutorials. If plausible, we'd like some instructions for interacting with the bridging functionalities of the rollup.

Thanks!

**Comment by kmurphypolygon** [comment]
Hi @sahil3Vedi you are absolutely right, thank you for raising this issue. We are working on adding bridging instructions to our docs. We should be able to address this after some upcoming releases. I'll keep this issue open and ping you when we have some developments.

**Comment by kmurphypolygon** [comment]
Hi @sahil3Vedi as part of our new documentation on the CDK kurtosis stack, there are now bridging instructions. This information is related to any CDK stack. Can you check it out here: https://docs.polygon.technology/cdk/get-started/how-to/use-native-token/. 

I'm gonna close this issue now but feel free to raise a new one if you have any trouble following the bridging instructions in our new doc.

Thank you :)
