### ISSUE TITLE
Update polygon mumbai RPC

### ISSUE THREAD

**Issue by 0xsiddharthks** [0xPolygon/polygon-docs-old#306]
The docs are still linking to a deprecated rpc for polygon mumbai: (https://rpc-mumbai.maticvigil.com/)

Same for the `Add Polygon Mumbai Network` button on https://mumbai.polygonscan.com/

https://docs.polygon.technology/tools/wallets/metamask/add-polygon-network/

**Comment by rube-de** [comment]
it's probably better to directly to change all to the new Amoy testnet

**Comment by 0xsiddharthks** [comment]
closing issue since Mumbai has already been deprecated.

**Comment by kmurphypolygon** [comment]
I'm going to reopen this issue as we are referring to Mumbai throughout PoS docs and Developer tools and these need to be updated. We have a ticket open for this now.

**Comment by Ayoseun** [comment]
Can you assign me this task.

**Comment by kmurphypolygon** [comment]
Hi, one of our writers has been working on this task. Thank you.

**Comment by kmurphypolygon** [comment]
Hi @Ayoseun and @0xsiddharthks, happy to let you know we've completed the work on this overall apart from on third-party apps and services which may take a little extra time.

Please keep your discussions, issues, and PRs coming in.

Thanks again :)
