### ISSUE TITLE
Mention the branch to use when deploying zkevm-contracts

### ISSUE THREAD

**Issue by amitOodles** [0xPolygon/polygon-docs-old#315]
I am going through the tutorial mentioned in the following link - 
https://docs.polygon.technology/zkEVM/get-started/deploy-zkevm/create-wallets/

In this article it is asked to take clone of the main branch of the zkevm-contracts repository, but the directory structure in the main branch is different from that mentioned in the doc. Also the deployment parameters file is also different from that used in the main branch

So can you confirm which branch should i use for deploying the contracts ?

**Comment by kmurphypolygon** [comment]
Hi there @amitOodles,  I'm so sorry you're experiencing these problems. Actually, this deployment guide is very out of date and we are in the process of updating it but it is taking time.

What you could do is use the CDK rollup guide, which is essentially the same guide: https://docs.polygon.technology/cdk/get-started/deploy-rollup/intro/

However, please note we are still working on updating the start services section in that guide.

Let us know if you have any issues with this guide and keep an eye out for updates.

Thank you for reaching out.
