### ISSUE TITLE
Errors in CDK Rollup instructions

### ISSUE THREAD

**Issue by sahil3vedi** [0xPolygon/polygon-docs-old#339]
_**Note:** The following query has been brought forward via dev-support. 
The docs in question are the CDK Rollup quickstart docs: https://docs.polygon.technology/cdk/get-started/quickstart-rollup/ 
Thanks a lot dear Polygon devs for your awesome work!_

Hi Team,

I am trying to set up the zk Rollup using cdk quicksetup to understand and explore the flow for near future utilizations.
I am facing the below challenges on setting it up in the EC2 instance:

1. The zk-Prover for unknown reasons exits immediately with 132 error . I am getting No logs from the container. Initially I raised this issue but When I moved to a new instance the issue seemed to be resolved and hence I closed the ticket. But the issue gets repeated and only solution is seemed to be moving to a new instance . 

2. After that when I run the command "make deploy-sc" the final submission of invalid transaction is throwing some error "The transaction would cause overdraft " after that I am not able to move further with the other commands.

3. When I tried commenting that final invalid transactions error part , the code seems to be working fine. Is that the required approach or is there any alternatives.

4. After all these steps I tried to run the explorers using the command "make run-explorer" the explorer containers are seems to be starting fine but there are no dats in the l2 explorer. I am getting the below error in the l2 explorer json rpc "Batch requests are disabled"

5. I was initially exploring the ZkEVM Node repo version v0.3.1 . It seemed to to be working fine in the local machine including the explorers. But with version 0.5.8 I am facing this issues 

6. I even tried to combine both the versions in the manner : running Node related containers from version 0.5.8 and explorers related containers from 0.3.1. I got the below error " Contract code is not available at the given address".
In both the cases There are no data in the l2 dbs.

Find the attached screenshots for references:  

![Screenshot (196)](https://github.com/0xPolygon/polygon-docs/assets/26119785/c249dbb7-7735-4dae-a785-9ee2803495c6)
![Screenshot (197)](https://github.com/0xPolygon/polygon-docs/assets/26119785/2f7bfd0b-16b9-4750-acd0-5822df3803ad)

**Comment by sahil3vedi** [comment]
hi @kmurphypolygon , 
kindly let us know if there can be a follow up to this query

Thanks for your time!

**Comment by kmurphypolygon** [comment]
Hi @sahil3Vedi thanks for your issue. Apologies, I was away last week. I will have a look for you this week. I suspect it is due to mismatch component versions. Back soon.

**Comment by kmurphypolygon** [comment]
Hi @sahil3Vedi I just went through the doc myself and I am encountering errors. I believe these are due to recent updates to the node. I will ask devs for more info on this and get back to you asap. Thank you for your patience.

**Comment by kmurphypolygon** [comment]
Hi @sahil3Vedi I have updated the doc. I managed to run everything on MacOS apart from the L2 explorers and bridge because they fail on ARM chips. I'm currently testing Ubuntu. Could you run through it again from scratch, without going onto a branch, i.e. a completely new clone, and let us know how you get on?

**Comment by Gokulakrishnan-Rajan** [comment]
Hi @kmurphypolygon , I am the one who raised this issue . Kindly let me know which branch I can test.

**Comment by kmurphypolygon** [comment]
Hi @Gokulakrishnan-Rajan you don't have to checkout any branch.

**Comment by kmurphypolygon** [comment]
btw @sahil3Vedi @Gokulakrishnan-Rajan this doc and content will be moving back into zkEVM docs in the next day or two ... the link will be here: https://docs.polygon.technology/zkEVM/get-started/setup-nodes/local-node/

**Comment by kmurphypolygon** [comment]
@sahil3Vedi and @Gokulakrishnan-Rajan hi there, please let me know if you managed to resolve your problems? Thank you :)

**Comment by kmurphypolygon** [comment]
Hi again @sahil3Vedi and @Gokulakrishnan-Rajan .. I'm gonna close this issue related to the old doc, and ask you to open a new one with any issues in the new document we published in the zkEVM section. I hope our new doc solves the problems :)
