### ISSUE TITLE
Unable to deploy the Polygon CDK stack due to port mapping error

### ISSUE THREAD

**Issue by hoarffrost** [0xPolygon/polygon-docs-old#416]
The concerned docs are regarding deployment of CDK stack: 
https://docs.polygon.technology/cdk/get-started/quickstart/deploy-stack/

Hey Devs,

I am trying to deploy the CDK stack on my local machine.
As I reached the [Check port mapping](https://docs.polygon.technology/cdk/get-started/quickstart/deploy-stack/#check-port-mapping) section of the page and ran the command...
```kurtosis port print cdk-v1 zkevm-node-rpc-001 http-rpc```

The error I encountered, 

```
  Caused by: An error occurred calling the run function for command 'print'
  Caused by: An error occurred while getting service context for service with identifier 'zkevm-node-rpc-001'
  Caused by: An error occurred when trying to get info for service 'zkevm-node-rpc-001'
  Caused by: rpc error: code = Unknown desc = Failed to get service info for service 'zkevm-node-rpc-001'
  Caused by: An error occurred getting info for service 'zkevm-node-rpc-001'
  Caused by: An error occurred while fetching registration for service identifier 'zkevm-node-rpc-001'
  Caused by: An error occurred while fetching name for service identifier 'zkevm-node-rpc-001'
  Caused by: Couldn't find a matching service name for identifier 'zkevm-node-rpc-001'

```
How to resolve this error, any guidance is appreciated👐

Looking forward to your response.

Thanks✌️

**Comment by kmurphypolygon** [comment]
Hi @Gyan313 did the previous instruction work for you? What do you see when you run `kurtosis enclave inspect cdk-v1
`? You should see output showing all the components and services and their state. If they're not running, do a `kurtosis clean -a`, maybe clean up Docker too, and try again.

**Comment by hoarffrost** [comment]
Thanks @kmurphypolygon for your response❤️. I did as you suggested and re-did every step in the [Deploy cdk stack ](https://docs.polygon.technology/cdk/get-started/quickstart/deploy-stack/#set-up). 
But when I tried running the command in Run the Kurtosis enclave `kurtosis run --enclave cdk-v1 --args-file params.yml --image-download always .` I got a big error possibly telling that there are multiple docker images that are not getting downloaded...

Error: 
```
There was an error validating Starlark code
Error while validating final environment of script
Caused by: Failed fetching the required image 'nulyjkdhthz/zkevm-bridge-ui:kurtosis'.
Caused by: An error occurred pulling image 'nulyjkdhthz/zkevm-bridge-ui:kurtosis'
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/metrics_reporting/metrics_reporting_kurtosis_backend.go:38 (MetricsReportingKurtosisBackend.FetchImage) ---
Caused by: An error occurred fetching image 'nulyjkdhthz/zkevm-bridge-ui:kurtosis'
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:1310 (DockerManager.FetchImage) ---
Caused by: Failed to pull Docker image 'nulyjkdhthz/zkevm-bridge-ui:kurtosis' from remote image repository.
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:1288 (DockerManager.FetchLatestImage) ---
Caused by: Tried pulling image 'nulyjkdhthz/zkevm-bridge-ui:kurtosis' but failed
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:1641 (DockerManager.pullImage) ---
Caused by: Tried pulling image 'nulyjkdhthz/zkevm-bridge-ui:kurtosis' with platform '' but failed
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:2301 (pullImage) ---
Caused by: Error response from daemon: Head "https://registry-1.docker.io/v2/nulyjkdhthz/zkevm-bridge-ui/manifests/kurtosis": Get "https://auth.docker.io/token?scope=repository%3Anulyjkdhthz%2Fzkevm-bridge-ui%3Apull&service=registry.docker.io": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
There was an error validating Starlark code
Error while validating final environment of script
Caused by: Failed fetching the required image 'grafana/grafana-enterprise:9.5.12'.
Caused by: An error occurred pulling image 'grafana/grafana-enterprise:9.5.12'
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/metrics_reporting/metrics_reporting_kurtosis_backend.go:38 (MetricsReportingKurtosisBackend.FetchImage) ---
Caused by: An error occurred fetching image 'grafana/grafana-enterprise:9.5.12'
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:1310 (DockerManager.FetchImage) ---
Caused by: Failed to pull Docker image 'grafana/grafana-enterprise:9.5.12' from remote image repository.
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:1288 (DockerManager.FetchLatestImage) ---
Caused by: Tried pulling image 'grafana/grafana-enterprise:9.5.12' but failed
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:1641 (DockerManager.pullImage) ---
Caused by: Tried pulling image 'grafana/grafana-enterprise:9.5.12' with platform '' but failed
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:2301 (pullImage) ---
Caused by: Error response from daemon: Head "https://registry-1.docker.io/v2/grafana/grafana-enterprise/manifests/9.5.12": Get "https://auth.docker.io/token?scope=repository%3Agrafana%2Fgrafana-enterprise%3Apull&service=registry.docker.io": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
There was an error validating Starlark code
There was an error validating Starlark code
Error while validating final environment of script
Caused by: Failed fetching the required image 'ethereum/client-go:latest'.
Caused by: An error occurred pulling image 'ethereum/client-go:latest'
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/metrics_reporting/metrics_reporting_kurtosis_backend.go:38 (MetricsReportingKurtosisBackend.FetchImage) ---
Caused by: An error occurred fetching image 'ethereum/client-go:latest'
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:1310 (DockerManager.FetchImage) ---
Caused by: Failed to pull Docker image 'ethereum/client-go:latest' from remote image repository.
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:1288 (DockerManager.FetchLatestImage) ---
Caused by: Tried pulling image 'ethereum/client-go:latest' but failed
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:1641 (DockerManager.pullImage) ---
There was an error validating Starlark code
Error while validating final environment of script
There was an error validating Starlark code
Error while validating final environment of script
Caused by: Failed fetching the required image 'minhdvu/panoptichain'.
Caused by: An error occurred pulling image 'minhdvu/panoptichain'
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/metrics_reporting/metrics_reporting_kurtosis_backend.go:38 (MetricsReportingKurtosisBackend.FetchImage) ---
Caused by: An error occurred fetching image 'minhdvu/panoptichain'
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:1310 (DockerManager.FetchImage) ---
Caused by: Failed to pull Docker image 'minhdvu/panoptichain:latest' from remote image repository.
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:1288 (DockerManager.FetchLatestImage) ---
Caused by: Tried pulling image 'minhdvu/panoptichain:latest' but failed
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:1641 (DockerManager.pullImage) ---
Caused by: Tried pulling image 'minhdvu/panoptichain:latest' with platform '' but failed
There was an error validating Starlark code
There was an error validating Starlark code
Error while validating final environment of script
Caused by: Failed fetching the required image 'leovct/zkevm-contracts:fork9'.
Caused by: An error occurred pulling image 'leovct/zkevm-contracts:fork9'
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/metrics_reporting/metrics_reporting_kurtosis_backend.go:38 (MetricsReportingKurtosisBackend.FetchImage) ---
Caused by: An error occurred fetching image 'leovct/zkevm-contracts:fork9'
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:1310 (DockerManager.FetchImage) ---
Caused by: Failed to pull Docker image 'leovct/zkevm-contracts:fork9' from remote image repository.
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:1288 (DockerManager.FetchLatestImage) ---
Caused by: Tried pulling image 'leovct/zkevm-contracts:fork9' but failed
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:1641 (DockerManager.pullImage) ---
Caused by: Tried pulling image 'leovct/zkevm-contracts:fork9' with platform '' but failed
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:2301 (pullImage) ---
There was an error validating Starlark code
There was an error validating Starlark code
Error while validating final environment of script
Caused by: Failed fetching the required image 'ethpandaops/ethereum-genesis-generator:3.0.3'.
Caused by: An error occurred pulling image 'ethpandaops/ethereum-genesis-generator:3.0.3'
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/metrics_reporting/metrics_reporting_kurtosis_backend.go:38 (MetricsReportingKurtosisBackend.FetchImage) ---
Caused by: An error occurred fetching image 'ethpandaops/ethereum-genesis-generator:3.0.3'
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:1310 (DockerManager.FetchImage) ---
Caused by: Failed to pull Docker image 'ethpandaops/ethereum-genesis-generator:3.0.3' from remote image repository.
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:1288 (DockerManager.FetchLatestImage) ---
Caused by: Tried pulling image 'ethpandaops/ethereum-genesis-generator:3.0.3' but failed
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:1641 (DockerManager.pullImage) ---
Caused by: Tried pulling image 'ethpandaops/ethereum-genesis-generator:3.0.3' with platform '' but failed
--- at /home/circleci/project/container-engine-lib/lib/backend_impls/docker/docker_manager/docker_manager.go:2301 (pullImage) ---
Caused by: Error response from daemon: Get "https://registry-1.docker.io/v2/ethpandaops/ethereum-genesis-genera

Container images used in this run:

> 0xpolygon/agglayer:0.1.3 - remotely downloaded
nulyjkdhthz/zkevm-bridge-ui:kurtosis - locally cached
postgres:16.2 - locally cached
ethereum/client-go:latest - locally cached
hermeznetwork/zkevm-prover:v6.0.0 - remotely downloaded
prom/prometheus:latest - remotely downloaded
protolambda/eth2-val-tools:latest - remotely downloaded
ethpandaops/ethereum-genesis-generator:3.0.3 - locally cached
0xpolygon/cdk-validium-node:0.6.5-cdk - locally cached
minhdvu/panoptichain - locally cached
leovct/zkevm-contracts:fork9 - locally cached
grafana/grafana-enterprise:9.5.12 - locally cached
hermeznetwork/zkevm-bridge-service:v0.4.2 - locally cached
badouralix/curl-jq - locally cached
haproxy:2.9.7 - remotely downloaded
0xpolygon/cdk-data-availability:0.0.7 - locally cached
sigp/lighthouse:latest - locally cached
python:3.11-alpine - remotely downloaded
makemake1337/blutgang:0.3.5 - remotely downloaded
> 

Error encountered running Starlark code.

⭐ us on GitHub - https://github.com/kurtosis-tech/kurtosis
INFO[2024-04-29T22:05:20+05:30] ===============================================
INFO[2024-04-29T22:05:20+05:30] ||          Created enclave: cdk-v1          ||
INFO[2024-04-29T22:05:20+05:30] ===============================================
Name:            cdk-v1
UUID:            5e7540eb3f11
Status:          RUNNING
Creation Time:   Mon, 29 Apr 2024 21:53:21 IST
Flags:

========================================= Files Artifacts =========================================
UUID   Name

========================================== User Services ==========================================
UUID   Name   Ports   Status
```
Can you tell me how to resolve this or point me in a direction where I can figure this out myself...Currently, I am reading kurtosis docs to resolve this...✌️

**Comment by kmurphypolygon** [comment]
Hi @Gyan313 thank you for letting us know, we'll have a look at this for you ... back soon.

**Comment by kmurphypolygon** [comment]
I've opened a ticket with the devs on this. Back soon.

**Comment by hoarffrost** [comment]
After a few tries, now I am getting this error: 
``` 
There was an error validating Starlark code 
Error while validating instruction get_services(). The instruction can be found at github.com/0xPolygon/kurtosis-cdk/observability.star[46:37]
        Caused by: Service 'blutgang-001' required by 'get_services' instruction doesn't exist
There was an error validating Starlark code 
Error while validating instruction get_services(). The instruction can be found at github.com/0xPolygon/kurtosis-cdk/observability.star[56:37]
        Caused by: Service 'blutgang-001' required by 'get_services' instruction doesn't exist


⭐ us on GitHub - https://github.com/kurtosis-tech/kurtosis
Name:            cdk-v1
UUID:            fd9809986474
Status:          RUNNING
Creation Time:   Tue, 30 Apr 2024 21:58:14 IST
Flags:           

========================================= Files Artifacts =========================================
UUID   Name

========================================== User Services ==========================================
UUID   Name   Ports   Status
```
Thanks for replying @kmurphypolygon 👐.

**Comment by leovct** [comment]
Hello @Gyan313, it looks like you're facing couple of issues.

> **🚨 edit: That may be related to the kurtosis version you're using!
  Be sure to check this link: https://github.com/0xPolygon/kurtosis-cdk/issues/96#issuecomment-2084482687**

To start with, I would first clean the environment.

```bash
kurtosis clean --all
```

Then, try to get the latest version of kurtosis-cdk.

```bash
git pull
```

Finally, you can start deploying the CDK stack. This will take a few minutes.

```bash
kurtosis run --enclave cdk-v1 --args-file params.yml --image-download always .
```

The command should execute successfully, but there might be an issue with our package or your setup. If that's the case, it would be great to have the logs of the command as well as your OS version and CPU model. For reference, this is the issue form we use for bugs: https://github.com/0xPolygon/kurtosis-cdk/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml

To confirm that everything worked, you can then run:

```bash
kurtosis enclave inspect cdk-v1
```

It should show all the different services and their ports.

From there, you can use `kurtosis port print ...`. It should work fine.

**Comment by kmurphypolygon** [comment]
Hi @Gyan313 I managed to recreate your issue on my machine (MacOS) and, for me, it was because I was running an older version of kurtosis cli and engine. You should have:

```
$ kurtosis version
CLI Version:   0.88.19

To see the engine version (provided it is running): kurtosis engine status
$ kurtosis engine status
A Kurtosis engine is running with the following info:
Version:   0.88.19
```

**Comment by hoarffrost** [comment]
Hi, guys @kmurphypolygon @leovct thanks for your help, I was able to get some services and artifacts because of downgrading the kurtosis cli version to `0.88.19`. But there are still some problems I am facing due to I am not able to get the `rpc url` and set up a permissionless node as suggested in polygon cdk docs. 
```
WARN[2024-05-04T21:56:12+05:30] You are running an old version of the Kurtosis CLI; we suggest you to update it to the latest version, '0.89.3'. You can manually upgrade the CLI tool following these instructions: https://docs.kurtosis.com/upgrade 
INFO[2024-05-04T21:56:12+05:30] No Kurtosis engine was found; attempting to start one... 
INFO[2024-05-04T21:56:12+05:30] Starting the centralized logs components...  
INFO[2024-05-04T21:56:12+05:30] Centralized logs components started.         
INFO[2024-05-04T21:56:12+05:30] Reverse proxy started.                       
INFO[2024-05-04T21:56:18+05:30] Successfully started Kurtosis engine         
INFO[2024-05-04T21:56:19+05:30] Executing Starlark package at '/home/gyandev/Desktop/startup/layer2_zk_rollup/kurtosis-cdk' as the passed argument '.' looks like a directory 
INFO[2024-05-04T21:56:19+05:30] Compressing package 'github.com/0xPolygon/kurtosis-cdk' at '.' for upload 
INFO[2024-05-04T21:56:21+05:30] Uploading and executing package 'github.com/0xPolygon/kurtosis-cdk' 
There was an error validating Starlark code 
Error while validating instruction get_services(). The instruction can be found at github.com/0xPolygon/kurtosis-cdk/observability.star[46:37]
        Caused by: Service 'blutgang-001' required by 'get_services' instruction doesn't exist
There was an error validating Starlark code 
Error while validating instruction get_services(). The instruction can be found at github.com/0xPolygon/kurtosis-cdk/observability.star[56:37]
        Caused by: Service 'blutgang-001' required by 'get_services' instruction doesn't exist

Error encountered running Starlark code.

⭐ us on GitHub - https://github.com/kurtosis-tech/kurtosis
Name:            cdk-v1
UUID:            da0a0d817554
Status:          RUNNING
Creation Time:   Sat, 04 May 2024 19:01:58 IST
Flags:         
========================================= Files Artifacts =========================================
UUID           Name
8edb39872062   1-lighthouse-geth-0-63
7e04b9ba6e6d   2-lighthouse-geth-64-127
bac40fdbfa4a   aggregator-keystore
1d593979593d   contract-deployment-script-artifact
3aef23952bd3   create-keystores-script-artifact
18dabdd9b12c   create-rollup-parameters-artifact
8259880378a1   dac-config-artifact
f0c2aac57038   dac-keystore
9f0ab02ef2f3   deploy-parameters-artifact
d90de3e51db4   el_cl_genesis_data
7349e29ea0ee   event-db-init.sql-001
80582ef76176   final-genesis-timestamp
512825791803   genesis
e96c273995a5   genesis-el-cl-env-file
a677c093180d   genesis_validators_root
60b209e6b3f0   jwt_file
b3328100b1b6   keymanager_file
93bb1885bb7b   proofsigner-keystore
de9aa602e4cf   prover-config-artifact
3285d9bff3f0   prover-db-init.sql-001
23af70ad9457   prysm-password
06f745694f31   sequencer-keystore
86c0e62b78c3   trusted-node-config
33c6b02f53d0   validator-ranges

========================================== User Services ==========================================
UUID           Name                                             Ports                                                  Status
dd12b7ebc5b1   agglayer-db-001                                  postgres: 5432/tcp -> postgresql://127.0.0.1:32790     STOPPED
a8da216a0684   bridge-db-001                                    postgres: 5432/tcp -> postgresql://127.0.0.1:32788     STOPPED
50458e3485f3   cl-1-lighthouse-geth                             http: 4000/tcp -> http://127.0.0.1:32781               STOPPED
                                                                metrics: 5054/tcp -> http://127.0.0.1:32780            
                                                                tcp-discovery: 9000/tcp -> 127.0.0.1:32779             
                                                                udp-discovery: 9000/udp -> 127.0.0.1:32770             
e6ed719c68c0   cl-2-lighthouse-geth                             http: 4000/tcp -> http://127.0.0.1:32784               STOPPED
                                                                metrics: 5054/tcp -> http://127.0.0.1:32783            
                                                                tcp-discovery: 9000/tcp -> 127.0.0.1:32782             
                                                                udp-discovery: 9000/udp -> 127.0.0.1:32771             
39966f11d08d   contracts-001                                    <none>                                                 STOPPED
8e15d8c7b6fd   dac-db-001                                       postgres: 5432/tcp -> postgresql://127.0.0.1:32789     STOPPED
c594355af1c5   el-1-geth-lighthouse                             engine-rpc: 8551/tcp -> 127.0.0.1:32771                STOPPED
                                                                metrics: 9001/tcp -> 127.0.0.1:32770                   
                                                                rpc: 8545/tcp -> http://127.0.0.1:32773                
                                                                tcp-discovery: 30303/tcp -> 127.0.0.1:32769            
                                                                udp-discovery: 30303/udp -> 127.0.0.1:32768            
                                                                ws: 8546/tcp -> 127.0.0.1:32772                        
3a271bc6d5be   el-2-geth-lighthouse                             engine-rpc: 8551/tcp -> 127.0.0.1:32776                STOPPED
                                                                metrics: 9001/tcp -> 127.0.0.1:32775                   
                                                                rpc: 8545/tcp -> http://127.0.0.1:32778                
                                                                tcp-discovery: 30303/tcp -> 127.0.0.1:32774            
                                                                udp-discovery: 30303/udp -> 127.0.0.1:32769            
                                                                ws: 8546/tcp -> 127.0.0.1:32777                        
497896bb56fe   event-db-001                                     postgres: 5432/tcp -> postgresql://127.0.0.1:32793     STOPPED
959e061dbd39   pool-db-001                                      postgres: 5432/tcp -> postgresql://127.0.0.1:32787     STOPPED
7d40d77a2273   prover-db-001                                    postgres: 5432/tcp -> postgresql://127.0.0.1:32792     STOPPED
1a6db3ea4f40   state-db-001                                     postgres: 5432/tcp -> postgresql://127.0.0.1:32791     STOPPED
890905ba998f   validator-key-generation-cl-validator-keystore   <none>                                                 STOPPED
1d10d03beae6   vc-1-lighthouse-geth                             metrics: 8080/tcp -> http://127.0.0.1:32785            STOPPED
3f2bee844410   vc-2-lighthouse-geth                             metrics: 8080/tcp -> http://127.0.0.1:32786            STOPPED
194df676089a   zkevm-node-synchronizer-001                      pprof: 6060/tcp -> http://127.0.0.1:32797              STOPPED
                                                                prometheus: 9091/tcp -> http://127.0.0.1:32796         
8e66b86f16da   zkevm-prover-001                                 executor-server: 50071/tcp -> grpc://127.0.0.1:32794   STOPPED
                                                                hash-db-server: 50061/tcp -> grpc://127.0.0.1:32795    
```

**Comment by kmurphypolygon** [comment]
> Hi, guys @kmurphypolygon @leovct thanks for your help, I was able to get some services and artifacts because of downgrading the kurtosis cli version to `0.88.19`. But there are still some problems I am facing due to I am not able to get the `rpc url` and set up a permissionless node as suggested in polygon cdk docs.
> 
> ```
> WARN[2024-05-04T21:56:12+05:30] You are running an old version of the Kurtosis CLI; we suggest you to update it to the latest version, '0.89.3'. You can manually upgrade the CLI tool following these instructions: https://docs.kurtosis.com/upgrade 
> INFO[2024-05-04T21:56:12+05:30] No Kurtosis engine was found; attempting to start one... 
> INFO[2024-05-04T21:56:12+05:30] Starting the centralized logs components...  
> INFO[2024-05-04T21:56:12+05:30] Centralized logs components started.         
> INFO[2024-05-04T21:56:12+05:30] Reverse proxy started.                       
> INFO[2024-05-04T21:56:18+05:30] Successfully started Kurtosis engine         
> INFO[2024-05-04T21:56:19+05:30] Executing Starlark package at '/home/gyandev/Desktop/startup/layer2_zk_rollup/kurtosis-cdk' as the passed argument '.' looks like a directory 
> INFO[2024-05-04T21:56:19+05:30] Compressing package 'github.com/0xPolygon/kurtosis-cdk' at '.' for upload 
> INFO[2024-05-04T21:56:21+05:30] Uploading and executing package 'github.com/0xPolygon/kurtosis-cdk' 
> There was an error validating Starlark code 
> Error while validating instruction get_services(). The instruction can be found at github.com/0xPolygon/kurtosis-cdk/observability.star[46:37]
>         Caused by: Service 'blutgang-001' required by 'get_services' instruction doesn't exist
> There was an error validating Starlark code 
> Error while validating instruction get_services(). The instruction can be found at github.com/0xPolygon/kurtosis-cdk/observability.star[56:37]
>         Caused by: Service 'blutgang-001' required by 'get_services' instruction doesn't exist
> 
> Error encountered running Starlark code.
> 
> ⭐ us on GitHub - https://github.com/kurtosis-tech/kurtosis
> Name:            cdk-v1
> UUID:            da0a0d817554
> Status:          RUNNING
> Creation Time:   Sat, 04 May 2024 19:01:58 IST
> Flags:         
> ========================================= Files Artifacts =========================================
> UUID           Name
> 8edb39872062   1-lighthouse-geth-0-63
> 7e04b9ba6e6d   2-lighthouse-geth-64-127
> bac40fdbfa4a   aggregator-keystore
> 1d593979593d   contract-deployment-script-artifact
> 3aef23952bd3   create-keystores-script-artifact
> 18dabdd9b12c   create-rollup-parameters-artifact
> 8259880378a1   dac-config-artifact
> f0c2aac57038   dac-keystore
> 9f0ab02ef2f3   deploy-parameters-artifact
> d90de3e51db4   el_cl_genesis_data
> 7349e29ea0ee   event-db-init.sql-001
> 80582ef76176   final-genesis-timestamp
> 512825791803   genesis
> e96c273995a5   genesis-el-cl-env-file
> a677c093180d   genesis_validators_root
> 60b209e6b3f0   jwt_file
> b3328100b1b6   keymanager_file
> 93bb1885bb7b   proofsigner-keystore
> de9aa602e4cf   prover-config-artifact
> 3285d9bff3f0   prover-db-init.sql-001
> 23af70ad9457   prysm-password
> 06f745694f31   sequencer-keystore
> 86c0e62b78c3   trusted-node-config
> 33c6b02f53d0   validator-ranges
> 
> ========================================== User Services ==========================================
> UUID           Name                                             Ports                                                  Status
> dd12b7ebc5b1   agglayer-db-001                                  postgres: 5432/tcp -> postgresql://127.0.0.1:32790     STOPPED
> a8da216a0684   bridge-db-001                                    postgres: 5432/tcp -> postgresql://127.0.0.1:32788     STOPPED
> 50458e3485f3   cl-1-lighthouse-geth                             http: 4000/tcp -> http://127.0.0.1:32781               STOPPED
>                                                                 metrics: 5054/tcp -> http://127.0.0.1:32780            
>                                                                 tcp-discovery: 9000/tcp -> 127.0.0.1:32779             
>                                                                 udp-discovery: 9000/udp -> 127.0.0.1:32770             
> e6ed719c68c0   cl-2-lighthouse-geth                             http: 4000/tcp -> http://127.0.0.1:32784               STOPPED
>                                                                 metrics: 5054/tcp -> http://127.0.0.1:32783            
>                                                                 tcp-discovery: 9000/tcp -> 127.0.0.1:32782             
>                                                                 udp-discovery: 9000/udp -> 127.0.0.1:32771             
> 39966f11d08d   contracts-001                                    <none>                                                 STOPPED
> 8e15d8c7b6fd   dac-db-001                                       postgres: 5432/tcp -> postgresql://127.0.0.1:32789     STOPPED
> c594355af1c5   el-1-geth-lighthouse                             engine-rpc: 8551/tcp -> 127.0.0.1:32771                STOPPED
>                                                                 metrics: 9001/tcp -> 127.0.0.1:32770                   
>                                                                 rpc: 8545/tcp -> http://127.0.0.1:32773                
>                                                                 tcp-discovery: 30303/tcp -> 127.0.0.1:32769            
>                                                                 udp-discovery: 30303/udp -> 127.0.0.1:32768            
>                                                                 ws: 8546/tcp -> 127.0.0.1:32772                        
> 3a271bc6d5be   el-2-geth-lighthouse                             engine-rpc: 8551/tcp -> 127.0.0.1:32776                STOPPED
>                                                                 metrics: 9001/tcp -> 127.0.0.1:32775                   
>                                                                 rpc: 8545/tcp -> http://127.0.0.1:32778                
>                                                                 tcp-discovery: 30303/tcp -> 127.0.0.1:32774            
>                                                                 udp-discovery: 30303/udp -> 127.0.0.1:32769            
>                                                                 ws: 8546/tcp -> 127.0.0.1:32777                        
> 497896bb56fe   event-db-001                                     postgres: 5432/tcp -> postgresql://127.0.0.1:32793     STOPPED
> 959e061dbd39   pool-db-001                                      postgres: 5432/tcp -> postgresql://127.0.0.1:32787     STOPPED
> 7d40d77a2273   prover-db-001                                    postgres: 5432/tcp -> postgresql://127.0.0.1:32792     STOPPED
> 1a6db3ea4f40   state-db-001                                     postgres: 5432/tcp -> postgresql://127.0.0.1:32791     STOPPED
> 890905ba998f   validator-key-generation-cl-validator-keystore   <none>                                                 STOPPED
> 1d10d03beae6   vc-1-lighthouse-geth                             metrics: 8080/tcp -> http://127.0.0.1:32785            STOPPED
> 3f2bee844410   vc-2-lighthouse-geth                             metrics: 8080/tcp -> http://127.0.0.1:32786            STOPPED
> 194df676089a   zkevm-node-synchronizer-001                      pprof: 6060/tcp -> http://127.0.0.1:32797              STOPPED
>                                                                 prometheus: 9091/tcp -> http://127.0.0.1:32796         
> 8e66b86f16da   zkevm-prover-001                                 executor-server: 50071/tcp -> grpc://127.0.0.1:32794   STOPPED
>                                                                 hash-db-server: 50061/tcp -> grpc://127.0.0.1:32795    
> ```

Hi @Gyan313 thanks for getting back to us. Just wondering where you got stuck exactly. Did you manage to update the parameters in the genesis file correctly to point to your L1 RPC URL? You should see the instruction for where that is in step 3 of [this section](https://github.com/SFranklinRoa).

**Comment by kmurphypolygon** [comment]
I'm going to close this ticket for now @Gyan313 as the original error is resolved. If you're still seeing the problem with the permissionless node documentation, please open another issue giving us all the details. Thank you :)
