### ISSUE TITLE
Snapshot docs are not correct

### ISSUE THREAD

**Issue by Evoolo** [0xPolygon/polygon-docs-old#558]
Hi, 

in [https://docs.polygon.technology/pos/how-to/snapshots/#downloading-and-using-client-snapshots](https://docs.polygon.technology/pos/how-to/snapshots/#downloading-and-using-client-snapshots) you mention the ability to use amoy in the --network flag. But if I do so, it asks me to use mumbai or mainnet. I think there is currently no snapshot provided for amoy. 

This should be mentioned in the docs.

**Comment by hsutaiyu** [comment]
Hi, @Evoolo ! Thanks for flagging this issue.

Testnet snapshots for Amoy testnet and beyond will be available via the community snapshot aggregator All4nodes.io, as specified in the docs [here](https://docs.polygon.technology/pos/how-to/snapshots/#community-snapshots). 

If you're looking for Amoy snapshots, please visit https://all4nodes.io/Polygon and choose a snapshot provided by any one of the active validators. Here's a direct link to StakePools' snapshot and instructions: https://docs.stakepool.dev.br/snapshots/polygon-amoy

Thanks for highlighting the error in the docs. As you pointed out, the `--network` flag for our snapshot CLI tool does not support the `amoy` option. We'll make that fix.

Feel free to re-open this issue if you have additional feedback.

Update: Issue addresses in PR #577
