### ISSUE TITLE
The snapshot links for the testnet are broken and redirect to an access denied page.

### ISSUE THREAD

**Issue by achiko** [0xPolygon/polygon-docs-old#572]
https://zkevm-pub.s3.eu-west-1.amazonaws.com/testnet-bridgedb.sql.gz (312MB)
https://zkevm-pub.s3.eu-west-1.amazonaws.com/testnet-statedb.sql.gz (1.9GB)
https://zkevm-pub.s3.eu-west-1.amazonaws.com/testnet-hashdb.sql.gz (49GB)

**Comment by EmpieichO** [comment]
@achiko Please note that we no longer have any new snapshots since February, 2024. 
Please refer to the notice added at the beginning of the snapshots document: https://docs.polygon.technology/zkEVM/get-started/state-sync-snapshots/
