### ISSUE TITLE
About malfunction resistence 

### ISSUE THREAD

**Issue by Ljiacheng** [0xPolygon/polygon-docs-old#586]
I have read this documentation [Malfunction resistence](https://docs.polygon.technology/zkEVM/architecture/protocol/malfunction-resistance/sequencer-resistance/).
Is there any tool to test this process? Send/sequence `ForceBatches` and generate proof to `VerifyBatchs`?

**Comment by EmpieichO** [comment]
Hi @Ljiacheng 

Thanks for your interest in the Polygon zkEVM. 
Here's a tool related to forced batches: https://github.com/0xPolygonHermez/code-examples/tree/main/force-batch-tool 

Please shout if you wish for more info. :-)

**Comment by Ljiacheng** [comment]
> Hi @Ljiacheng
> 
> Thanks for your interest in the Polygon zkEVM. Here's a tool related to forced batches: https://github.com/0xPolygonHermez/code-examples/tree/main/force-batch-tool
> 
> Please shout if you wish for more info. :-)

Hi @EmpieichO 

Thanks for your reply! But it seems not enough to finish the process. How can I generate proofs for forced batches? Current **zkevm-aggregator** only send trusted aggregator's proof to L1. For a user to proof forced batches, what should I do?

**Comment by EmpieichO** [comment]
Noted. 
@krlosMata, I believe you can help here.

**Comment by krlosMata** [comment]
Forced batches are submitted by the user.
Later on, sequencer adds those forced batches into a sequence that is submitted to L1.
Smart contract gives the possibikity to the sequencer to add the forced batch. Otherwise, the forced batch could be sequenced by anyone.

The aggregator does its tasks regardless the batch, either forced or not.

**Comment by Ljiacheng** [comment]
> Forced batches are submitted by the user. Later on, sequencer adds those forced batches into a sequence that is submitted to L1. Smart contract gives the possibikity to the sequencer to add the forced batch. Otherwise, the forced batch could be sequenced by anyone.
> 
> The aggregator does its tasks regardless the batch, either forced or not.

@krlosMata Thanks for your help!
But my biggest problem is how to get zk-proofs from zkevm-prover. 
To `claimAsset`, the `globalExitRoot` should be updated. The smart contract [PolygonRollupManager.sol](https://github.com/0xPolygonHermez/zkevm-contracts/blob/v6.0.0-rc.1-fork.9/contracts/v2/PolygonRollupManager.sol) shows that only `verifyBatchesTrustedAggregator` and `verifyBatches` can update root which need proofs. 
contract version: [zkevm-contracts(v6.0.0-rc.1-fork.9)](https://github.com/0xPolygonHermez/zkevm-contracts/tree/v6.0.0-rc.1-fork.9)

**Comment by krlosMata** [comment]
Mmm...I guess you are running the aggregator software and somehow it is no generating any proof.
Are you running the full system or do you want to test forceBatches function ?

If you are running the full system...then the aggregator will be the trusted Aggrehator and call verifyBatchesTrustedAggregator. Maybe checking the logs of the aggregator, there could be some valuable info there about why is not generating proofs

**Comment by Ljiacheng** [comment]
> Mmm...I guess you are running the aggregator software and somehow it is no generating any proof. Are you running the full system or do you want to test forceBatches function ?
> 
> If you are running the full system...then the aggregator will be the trusted Aggrehator and call verifyBatchesTrustedAggregator. Maybe checking the logs of the aggregator, there could be some valuable info there about why is not generating proofs

I know trusted aggregator can send proofs by  `verifyBatchesTrustedAggregator`. 
But what I want is sending proofs by `verifyBatches` as a normal user(not trusted aggregator). To send this transaction, I need to generate zk-proofs. The code of zkevm-aggregator seems can't handle this situation...
