### ISSUE TITLE
About Bundle 1 confirmation and Bundle 2 confirmation

### ISSUE THREAD

**Issue by VetchM** [0xPolygon/polygon-docs-old#620]
When I trading MATIC in Binace APP, the confirmation of the transaction shows "Bundle 1" and "Bundle 2". It's usually are number of block that it need to be comfirmed. What is this "Bundle 1" and "Bundle 2" means? How long is "Bundle 1" and how long is "Bundle 2"? 
<img width="384" alt="160526" src="https://github.com/user-attachments/assets/63be7e68-7e85-4674-a410-fb9ed8c768fc">

**Comment by kmurphypolygon** [comment]
Hi @VetchM did you ask Binance for confirmation yet?

**Comment by VetchM** [comment]
> Hi @VetchM did you ask Binance for confirmation yet?

Yes, I asked in their forum. Their reply was: "The time required to reach a Layer 2 confirmation in a blockchain can vary significantly depending on several factors, including the network's current load and the underlying blockchain's confirmation times." I couldn't find anything releated in Google or Polygon docs, so I asked here.

**Comment by kmurphypolygon** [comment]
Hi @VetchM it looks to me like their system has two types of confirmation, the first one allows you to trade the funds you deposited in the Binance system but not yet withdraw them, and the second one is a stronger confirmation that allows you to withdraw your funds also. I'm guessing it's related to number of confirmations but it's impossible to know for sure, only Binance can tell you this.

Although you could also check the transaction links on the explorer, if they provide that, and figure it out.

**Comment by VetchM** [comment]
> Hi @VetchM it looks to me like their system has two types of confirmation, the first one allows you to trade the funds you deposited in the Binance system but not yet withdraw them, and the second one is a stronger confirmation that allows you to withdraw your funds also. I'm guessing it's related to number of confirmations but it's impossible to know for sure, only Binance can tell you this.
> 
> Although you could also check the transaction links on the explorer, if they provide that, and figure it out.

Thanks!
